### PR TITLE
FBCM-5195 Setup Spago Project

### PR DESCRIPTION
**Pull request by boygao1992**
## What does this pull request do?

Initialize the PS project with `spago` and `purs-tidy` and add a `Makefile`. Add `kafkajs` repo as a submodule so that we can use the docker compose file that `kafkajs` uses to test our own code. Add `Test.Main` that automatically prepares Zookeeper and Kafka in the environment ready to connect to producers/consumers. Add documentation on basic shell commands for people new to Kafka to play with.

## How should this be manually tested?

- [ ] no `nix` set up yet so you need `docker` and `docker-compose` [installed](https://docs.docker.com/compose/install/)
- [ ] `make build`
  - should download `npm` and `spago` dependencies and build PS code
- [ ] `make test`
  - should start Zookeeper and Kafka, wait for brokers `kafka1`, `kafka2`, `kafka3` to be ready, and then stop Zookeeper and Kafka
- [ ] (optional) try out commands under `docs/shell-commands.md`

### CODE REVIEW

**Comment by citizengabe** [comment]
I still don't think we need to test against a running Kafka instance in a wrapper library. We might want to test any abstractions we build atop `kafkajs`, but we have to assume that library works as documented.

I think it _does_ make sense to have these sorts of tests in a consuming application though.

**Comment by boygao1992** [comment]
> I still don't think we need to test against a running Kafka instance in a wrapper library. We might want to test any abstractions we build atop `kafkajs`, but we have to assume that library works as documented.

But I don't think we have enough knowledge of Kafka to reason about invariants over the low level and `kafkajs` library is not well documented for beginners. Like I mentioned before, I immediately ran into problem when trying out the Hello World example in the [Get Started doc](https://kafka.js.org/docs/getting-started). And there are inconsistencies in the docs for developers. Like [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md) uses `docker-compose` with docker images from `confluentinc` but [DockerLocal](https://github.com/tulios/kafkajs/blob/master/docs/DockerLocal.md), which is mentioned in [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md), still uses docker images from `wurstmeister` which is no longer recommended as the last Kafka version they provide (`2.8.1`) is way behind the latest (`3.3.1`) and requires one to manually compute `HOST_IP`.

I want a test suite that has enough examples to cover our use cases so whoever else getting started can pick up from there instead of going through all the docs.

**Review by afcondon — APPROVED** [review]
Tested this and discovered that Docker on the Mac seems to be in much worse shape than i was anticipating two years after first ARM-based Macs shipped. However, after working with Wenbo to trouble-shoot we identified the appropriate time-limits such that the tests in this PR worked for me and should work for other Mac users.

**Comment by boygao1992** [comment]
Thanks for the review!

**Comment by citizengabe** [comment]
> Like [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md) uses `docker-compose` with docker images from `confluentinc` but [DockerLocal](https://github.com/tulios/kafkajs/blob/master/docs/DockerLocal.md), which is mentioned in [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md), still uses docker images from `wurstmeister` which is no longer recommended as the last Kafka version they provide (`2.8.1`) is way behind the latest (`3.3.1`)

Did you try the instructions from [DockerLocal](https://github.com/tulios/kafkajs/blob/master/docs/DockerLocal.md) using the image from [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md)?

**Comment by boygao1992** [comment]
> Did you try the instructions from [DockerLocal](https://github.com/tulios/kafkajs/blob/master/docs/DockerLocal.md) using the image from [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md)?

That won't work because `KAFKA_ADVERTISED_HOST_NAME` and `KAFKA_ADVERTISED_PORT` in the example `docker-compose.yml` are deprecated in newer versions as documented at the end of [wurstmeister's Kafka connectivity doc](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity#internal-versus-advertised). The image from [DevelopmentEnvironment](https://github.com/tulios/kafkajs/blob/master/docs/DevelopmentEnvironment.md) is from `concluentinc` which doesn't require specifying `HOST_IP` (no occurrence of `${HOST_IP}` env param in its `docker-compose.yml`).

**Pull request merged**
